name: Link checks
on: [push]

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.md-link-check.json'
