name: Linters
on: [push]

jobs:
  prose:
    name: Prose lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.0
      with:
        styles: https://github.com/errata-ai/proselint/releases/download/v0.3.2/proselint.zip
        onlyAnnotateModifiedLines: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
